site_name: Sam Rambles
site_url: https://samrambles.com
site_description: Technology Writing
site_author: Sumanth "Sam" Peddamatham
copyright: Made with ❤️ by Sam.
repo_name: peddamat/mkdocs-obsidian
repo_url: https://github.com/peddamat/mkdocs-obsidian
edit_uri: edit/main/docs/
docs_dir: ./notes
site_dir: ./site

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: white
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - header.autohide         # Hide header when scrolling down
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tracking     # Reflect current #section in URL
    - navigation.top          # Back-to-top button
    - navigation.sections     # Expands sections in left-sidebar
    - navigation.tabs         # Sections in header
    - toc.integrate           # Moves toc from right sidebar to left
    # - navigation.instant
    # - toc.follow            # Doesn't seem to work
    # - navigation.path         # Breadcrumb above page title
  font:
    text: Noto Sans
    code: IMB Plex Mono

plugins:
  # Resolves Obsidian [[wikilinks]]
  - roamlinks
  - awesome-pages
  - minify:
      minify_html: true
  - tags:
      tags_file: tags.md
      # Below are insiders-only settings
      # tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower

  - search:
      prebuild_index: python  # Adds 100Kb to site
      indexing: titles
      separator: '[\s\-\.]+'
      lang:
        - en
  - blogging:
      dirs: # The directories to be included
        - .
      template: overrides/custom-blog.html
      features:
        tags:
          index_page: tags.md
          insert: bottom

      # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
      # categories:
      #   - name: reviews
      #     dirs:
      #       - reviews

      # GLOBAL CONFIG: configs apply to all categories
      time_format: '%m/%d/%y %H:%M:%S'
      meta_time_format: '%m/%d/%y %H:%M:%S'

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/peddamat
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/peddamat

markdown_extensions:
  # Table of contents
  - toc:
      permalink: true
  # Source code boxes
  - pymdownx.superfences
  # Syntax highlighting
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - meta
  - admonition
  - attr_list
  - def_list
  - footnotes

  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
  # - stylesheets/hide_nav.css

hooks:
  - hooks/flatten_filenames.py
  - hooks/only_include_published.py
