site_name: Sam Rambles
site_url: https://samrambles.com
site_description: Technology Writing
site_author: Sumanth "Sam" Peddamatham
copyright: Made with ❤️ by Sam.
repo_name: peddamat/mkdocs-obsidian
repo_url: https://github.com/peddamat/mkdocs-obsidian
edit_uri: edit/main/docs/
docs_dir: ./notes
site_dir: ./site

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: white
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  shortcuts:
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  language: en
  include_search_page: true
  search_index_only: true
  features:
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tracking
    - navigation.top
    - navigation.sections
    # - navigation.instant
    - toc.follow
    # - toc.integrate
  font:
    text: Noto Sans
    code: IMB Plex Mono

plugins:
  # - search:
  #     separator: '[\s\-\.]+'
  #     prebuild_index: python
  #     lang:
  #       - en
  - minify:
      minify_html: true
  - roamlinks
  - blogging:
      dirs: # The directories to be included
        - .
      template: overrides/custom-blog.html

      # INDIVIDUAL CATEGORIES: configs for {{ blog_content name }}
      # categories:
      #   - name: reviews
      #     dirs:
      #       - reviews

      # GLOBAL CONFIG: configs apply to all categories
      time_format: '%d/%m/%y %H:%M:%S'
      meta_time_format: '%Y-%m-%d %H:%M:%S'
      # features:
      #   tags:
      #     index_page: tags.md
      #     insert: top

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mr-karan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mrkaran_

markdown_extensions:
  - admonition
  - codehilite
  - meta
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  # - pymdownx.tasklist
  - toc:
      permalink: true
  # Added below
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css
  - stylesheets/hide_nav.css

hooks:
  - hooks/flatten_filenames.py
  - hooks/only_include_published.py
